<a href="https://colab.research.google.com/github/wahiwatkar06-gif/mdm-practicals/blob/main/practical_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Decision tree

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import plot_tree

In [ ]:
data = pd.read_csv("/content/wireless_signal_quality_dataset (2).csv")
print("first five records")
print(data.head())
print("\nDataset Shape")

first five records
   Signal_Strength_dBm  SNR_dB  Interference_dB  Distance_m  Frequency_GHz  \
0                  -41       6                0         257            5.0
1                  -86      25               20         134            2.4
2                  -73      27                0         385            2.4
3                  -57       5                0         255            5.0
4                  -87      15               24          61            5.0

   Channel_Bandwidth_MHz  Noise_Floor_dBm  Connected_Devices  \
0                    160             -100                 24
1                    160              -96                 41
2                     20              -72                 13
3                    160              -86                  9
4                     20              -79                 32

   Estimated_Throughput_Mbps Quality
0                         18    Poor
1                         55    Poor
2                         81    Fair
3                         15    Poor
4                         21    Poor

Dataset Shape

In [ ]:
x=data.drop('Quality',axis=1)
y=data['Quality']

encoder = LabelEncoder()
y=encoder.fit_transform(y)

print("\nClass Labels:")
print(encoder.classes_)

Class Labels:
['Excellent' 'Fair' 'Good' 'Poor']

In [ ]:
data.head()

,Signal_Strength_dBm,SNR_dB,Interference_dB,Distance_m,Frequency_GHz,Channel_Bandwidth_MHz,Noise_Floor_dBm,Connected_Devices,Estimated_Throughput_Mbps,Quality
0,-41,6,0,257,5.0,160,-100,24,18,Poor
1,-86,25,20,134,2.4,160,-96,41,55,Poor
2,-73,27,0,385,2.4,20,-72,13,81,Fair
3,-57,5,0,255,5.0,160,-86,9,15,Poor
4,-87,15,24,61,5.0,20,-79,32,21,Poor

In [ ]:
#Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [ ]:
#Train Decision tree
dt = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42
)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [ ]:
#Prediction
y_pred = dt.predict(X_test)

In [ ]:
#Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: {:.2f}%".format(accuracy*100))

Accuracy: 92.00%

In [ ]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

Confusion Matrix:
[[ 0  0  1  0]
 [ 0  8  1  0]
 [ 0  0  2  0]
 [ 0  0  0 13]]

In [ ]:
#classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred,target_names=encoder.classes_))

Classification Report:
              precision    recall  f1-score   support

   Excellent       0.00      0.00      0.00         1
        Fair       1.00      0.89      0.94         9
        Good       0.50      1.00      0.67         2
        Poor       1.00      1.00      1.00        13

    accuracy                           0.92        25
   macro avg       0.62      0.72      0.65        25
weighted avg       0.92      0.92      0.91        25

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#Feature importance
importances = pd.Series(
    dt.feature_importances_,
    index=x.columns
)
importances = importances.sort_values(ascending=False)
print("\nFeature Importance:")
print(importances)

Feature Importance:
Signal_Strength_dBm          0.438873
SNR_dB                       0.365448
Estimated_Throughput_Mbps    0.117036
Interference_dB              0.078643
Distance_m                   0.000000
Frequency_GHz                0.000000
Channel_Bandwidth_MHz        0.000000
Noise_Floor_dBm              0.000000
Connected_Devices            0.000000
dtype: float64

In [ ]:
print(data.isnull().sum())

Signal_Strength_dBm          0
SNR_dB                       0
Interference_dB              0
Distance_m                   0
Frequency_GHz                0
Channel_Bandwidth_MHz        0
Noise_Floor_dBm              0
Connected_Devices            0
Estimated_Throughput_Mbps    0
Quality                      0
dtype: int64

In [ ]:
#check file loaded as a 1 column
if len(data.columns) == 1:
  print("incorrect csv format detected. repairing ....")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Signal_Strength_dBm        100 non-null    int64
 1   SNR_dB                     100 non-null    int64
 2   Interference_dB            100 non-null    int64
 3   Distance_m                 100 non-null    int64
 4   Frequency_GHz              100 non-null    float64
 5   Channel_Bandwidth_MHz      100 non-null    int64
 6   Noise_Floor_dBm            100 non-null    int64
 7   Connected_Devices          100 non-null    int64
 8   Estimated_Throughput_Mbps  100 non-null    int64
 9   Quality                    100 non-null    object
dtypes: float64(1), int64(8), object(1)
memory usage: 7.9+ KB

In [ ]:
data.describe()

,Signal_Strength_dBm,SNR_dB,Interference_dB,Distance_m,Frequency_GHz,Channel_Bandwidth_MHz,Noise_Floor_dBm,Connected_Devices,Estimated_Throughput_Mbps
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.00000,100.000000,100.000000
mean,-69.020000,21.150000,14.490000,264.500000,4.34400,64.200000,-84.80000,24.390000,49.590000
std,16.318162,10.641424,9.090449,136.653399,1.51866,46.562221,9.05427,14.537235,33.001713
min,-95.000000,5.000000,0.000000,17.000000,2.40000,20.000000,-100.00000,1.000000,1.000000
25%,-84.250000,11.750000,7.000000,158.750000,2.40000,20.000000,-93.25000,11.000000,22.750000
50%,-69.500000,19.500000,14.000000,270.500000,5.00000,40.000000,-84.50000,23.500000,49.000000
75%,-55.000000,31.000000,21.250000,370.500000,6.00000,80.000000,-76.00000,37.250000,78.250000
max,-40.000000,40.000000,30.000000,499.000000,6.00000,160.000000,-70.00000,50.000000,112.000000